# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
oss_performance_mediawiki:
  parser: mediawiki
  install_script: ./packages/mediawiki/install_oss_performance_mediawiki.sh
  cleanup_script: ./packages/mediawiki/cleanup_oss_performance_mediawiki.sh
  install_markers:
    - ./oss-performance/perf.php
    - ./oss-performance/base/PerfRunner.php
    - ./oss-performance/composer.phar
  path: ./packages/mediawiki/run.sh
  tags:
    scope:
      - app
      - web
    component:
      - cpu
  metrics: []

django_workload:
  parser: django_workload
  check_returncode: false
  install_script: ./packages/django_workload/install_django_workload.sh
  cleanup_script: ./packages/django_workload/cleanup_django_workload.sh
  install_markers:
    - ./benchmarks/django_workload/bin/run.sh
    - ./benchmarks/django_workload/proxygen_binding/proxygen_binding*.so
    - ./benchmarks/django_workload/django-workload/django-workload/django_workload/thrift/build/gen-py3/mock_services/MockAdsService-remote
    - ./benchmarks/django_workload/django-workload/django-workload/django_workload/feed_timeline.py
    - ./benchmarks/django_workload/django-workload/django-workload/cinder/cinder-build/bin/python3.14
    - ./benchmarks/django_workload/django-workload/django-workload/Python-3.14.2/python-build/bin/python3.14
    - ./benchmarks/django_workload/wrk/wrk
    - ./benchmarks/django_workload/apache-cassandra/bin/cassandra
  path: ./benchmarks/django_workload/bin/run.sh
  tags:
    scope:
      - app
      - django
    component:
      - cpu
  metrics: []

tao_bench:
  parser: tao_bench
  install_script: ./packages/tao_bench/install_tao_bench.sh
  cleanup_script: ./packages/tao_bench/cleanup_tao_bench.sh
  install_markers:
    - ./benchmarks/tao_bench/tao_bench_server
    - ./benchmarks/tao_bench/tao_bench_client
  path: ./packages/tao_bench/run.py
  tags:
    scope:
      - app
      - cache
    component:
      - cpu
      - memory
  metrics: []
  roles:
    - server
    - client

tao_bench_autoscale:
  parser: tao_bench_autoscale
  install_script: ./packages/tao_bench/install_tao_bench.sh
  cleanup_script: ./packages/tao_bench/cleanup_tao_bench.sh
  path: ./packages/tao_bench/run_autoscale.py
  tags:
    scope:
      - app
      - cache
    component:
      - cpu
      - memory
  metrics: []

tao_bench_standalone:
  parser: tao_bench_autoscale
  install_script: ./packages/tao_bench/install_tao_bench.sh
  cleanup_script: ./packages/tao_bench/cleanup_tao_bench.sh
  path: ./packages/tao_bench/run_standalone.py
  tags:
    scope:
      - app
      - cache
    component:
      - cpu
      - memory
  metrics: []

feedsim:
  parser: feedsim
  install_script: ./packages/feedsim/install_feedsim.sh
  cleanup_script: ./packages/feedsim/cleanup_feedsim.sh
  install_markers:
    - ./benchmarks/feedsim/src/build/workloads/ranking/LeafNodeRank
    - ./benchmarks/feedsim/src/build/workloads/ranking/DriverNodeRank
  path: ./benchmarks/feedsim/run.sh
  tags:
    scope:
      - app
      - feed
    component:
      - cpu
      - memory
  metrics:
    - target_percentile
    - target_latency_msec
    - final_requested_qps
    - final_achieved_qps
    - final_latency_msec

feedsim_autoscale:
  parser: feedsim_autoscale
  install_script: ./packages/feedsim/install_feedsim.sh
  cleanup_script: ./packages/feedsim/cleanup_feedsim.sh
  path: ./benchmarks/feedsim/run-feedsim-multi.sh
  tags:
    scope:
      - app
      - feed
    component:
      - cpu
      - memory
  metrics:
    - target_percentile
    - target_latency_msec
    - final_requested_qps
    - final_achieved_qps
    - final_latency_msec


spark_standalone:
  parser: spark_standalone
  install_script: ./packages/spark_standalone/install_spark_standalone.sh
  cleanup_script: ./packages/spark_standalone/cleanup_spark_standalone.sh
  install_markers:
    - ./benchmarks/spark_standalone/spark-4.0.2-bin-hadoop3/bin/spark-sql
    - ./benchmarks/spark_standalone/scripts/run_perf_common.py
    - /usr/lib/jvm/graalvm-community-openjdk-17.0.9+9.1/bin/java
  path: ./packages/spark_standalone/templates/runner.py
  tags:
    scope:
      - app
    component:
      - cpu
      - memory
  metrics: []


video_transcode_bench:
  parser: video_transcode_bench
  install_script: ./packages/video_transcode_bench/install_video_transcode_bench.sh
  cleanup_script: ./packages/video_transcode_bench/cleanup_video_transcode_bench.sh
  path: ./benchmarks/video_transcode_bench/run.sh
  tags:
    scope:
      - app
      - ffmpeg
    component:
      - cpu
      - memory
  metrics: []

health_check:
  parser: health_check
  install_script: ./packages/health_check/install_health_check.sh
  cleanup_script: ./packages/health_check/cleanup_health_check.sh
  path: ./benchmarks/health_check/run.sh
  metrics: []

sleep:
  path: /usr/bin/sleep
  parser: returncode
  metrics: []
