fbgemm_embedding:
  parser: embedding
  install_script: ./packages/fbgemm_gpu/install_embedding.sh
  cleanup_script: ./packages/fbgemm_gpu/cleanup_embedding.sh
  path: ./benchmarks/fbgemm_embedding/tbe_inference_benchmark
  metrics:
    - bandwidth

rebatch:
  parser: rebatch
  install_script: ./packages/rebatch/install_rebatch.sh
  cleanup_script: ./packages/rebatch/cleanup_rebatch.sh
  path: ./benchmarks/rebatch/rebatchBench
  metrics:
    - bandwidth
    - time_per_batch_us
