- benchmark: oss_performance_mediawiki
  name: oss_performance_mediawiki
  description: Default run for oss_performance_mediawiki
  args:
    - '-r/usr/local/hphpi/legacy/bin/hhvm'
    - '-nnginx'
    - '-ssiege'
    - '--'
    - '--mediawiki'
    - '--siege-duration=10M'
    - '--siege-timeout=11m'
    - '--run-as-root'
    - '--i-am-not-benchmarking'

- benchmark: oss_performance_mediawiki
  name: oss_performance_mediawiki_mlp
  description: Tuned +MLP run for oss_performance_mediawiki
  args:
    - '-r/usr/local/hphpi/legacy/bin/hhvm'
    - '-nnginx'
    - '-ssiege'
    - '--'
    - '--mediawiki-mlp'
    - '--siege-duration=10M'
    - '--siege-timeout=11m'
    - '--run-as-root'
    - '--i-am-not-benchmarking'

- benchmark: oss_performance_mediawiki
  name: oss_performance_mediawiki_mem
  description: Tuned +(MLP+LambdaChase) run for oss_performance_mediawiki
  args:
    - '-r/usr/local/hphpi/legacy/bin/hhvm'
    - '-nnginx'
    - '-ssiege'
    - '--'
    - '--mediawiki-mem'
    - '--siege-duration=10M'
    - '--siege-timeout=11m'
    - '--run-as-root'
    - '--i-am-not-benchmarking'

- benchmark: django_workload
  name: django_workload_default
  description: Default run for django-workload
  tee_output: true
  roles:
    clientserver:
      args:
        - '-r clientserver'
        - '-d 5M'
        - '-l ./siege.log'
        - '-s urls.txt'
        - '-c {db_addr}'
      vars:
        - 'db_addr'
    db:
      args:
        - '-r db'

- name: feedsim_default
  benchmark: feedsim
  description: >
    Aggregator like workload. Latency sensitive.
    Finds maximum QPS that system can sustain while keeping
    95th percentile latency <= 500 msecs.
  args: []
  hooks:
    - hook: cpu-mpstat
      options:
        args:
          - '-u'   # utilization
          - '1'    # second interval

- benchmark: spark_standalone
  name: spark_standalone_local
  description: Spark standalone using local SSDs for database and shuffling point
  args:
    - 'run'
    - '--real'

- benchmark: spark_standalone
  name: spark_standalone_remote_setup
  description: Instructions to setup to use remote SSDs via NVMe-over-TCP
  args:
    - 'setup'

- benchmark: spark_standalone
  name: spark_standalone_remote
  description: Spark standalone using remote SSDs for database and shuffling point; compute & memory bound as in prod
  args:
    - 'run'
    - '--dataset-path /flash23/'
    - '--warehouse-dir /flash23/warehouse'
    - '--shuffle-dir /flash23/spark_local_dir'
    - '--real'

- benchmark: spark_standalone
  name: spark_standalone_remote_compute
  description: Spark standalone using remote SSDs for database and shuffling point; compute bound only
  args:
    - 'run'
    - '--dataset-path /flash23/'
    - '--warehouse-dir /flash23/warehouse'
    - '--shuffle-dir /flash23/spark_local_dir'
    - '--aggressive 1'
    - '--real'

- benchmark: tao_bench
  name: tao_bench_64g
  description:
      Tao benchmark using 64GB memory.
      MAKE SURE to start clients within 1 minute.
  roles:
    server:
      args:
        - 'server'
        - '--memsize=64'
        - '--nic-channel-ratio=0.5'
        - '--fast-threads-ratio=0.75'
        - '--dispatcher-to-fast-ratio=0.25'
        - '--slow-to-fast-ratio=3'
        - '--interface-name={interface_name}'
        - '--real'
      vars:
        - 'interface_name'
    client:
      args:
        - 'client'
        - '--server-hostname={server_hostname}'
        - '--server-memsize=64'
        - '--target-hit-ratio=0.9'
        - '--tunning-factor=0.807'
        - '--warmup-time=1200'
        - '--test-time=360'
        - '--real'
      vars:
        - 'server_hostname'

- benchmark: memcached_bench
  name: memcached_bench_64g
  description:
      MemCache benchmark using 64GB memory
      Killing server in 27 mins,
      MAKE SURE to start clients within 1 minute
  roles:
    server:
      args:
        - 'server'
        - '--memsize=64'
        - '--mem-holdback=7.5'
        - '--num-bw-threads=2'
        - '--warmup-time=1200'
        - '--test-time=360'
        - '--real'
    client:
      args:
        - 'client'
        - '--server-hostname={server_hostname}'
        - '--server-memsize=64'
        - '--server-mem-holdback=7.5'
        - '--target-hit-ratio=0.5'
        - '--tunning-factor=0.98'
        - '--warmup-time=1200'
        - '--test-time=360'
        - '--real'
      vars:
        - 'server_hostname'
